octomap_server:
  ros__parameters:
    frame_id: odom
    base_frame_id: base_link
    resolution: 0.4
    max_depth: 16
    latch: true
    compress_map: true
    publish_free_space: false
    filter_ground_plane: false
    filter_speckles: false
    use_height_map: false
    colored_map: false
    incremental_2D_projection: false
    point_cloud_min_x: -30.0
    point_cloud_max_x: 30.0
    point_cloud_min_y: -30.0
    point_cloud_max_y: 30.0
    point_cloud_min_z: -20.0
    point_cloud_max_z: 20.0
    occupancy_min_z: -20.0
    occupancy_max_z: 20.0
    sensor_model:
      max_range: 20.0
      hit: 0.7
      miss: 0.4
      min: 0.12
      max: 0.97
